data_configs:
    dataset_dir: '/home/hankm/data/neuro_globalplan/train_dataset/data4/processed_data'
    gmheight: 480
    gmwidth: 480
    gmheight_p: 512
    gmwidth_p: 512
    pad_size: 16
    maplens: [400,400,400,400,400,480] # map sizes (height = width) for all images in explore bench dataset
    num_rounds: 100
    metalen: 18
    worlds: ['loop', 'room_with_corner', 'room', 'corner', 'corridor', 'loop_with_corridor']
    fr_size_thr: 8

network_configs:
    input_channels: 2
    output_channels: 1  # num classes (continous potmap resolution)
    batch_size: 8
    num_filters: 16
    batch_norm: false
    loss_weights: [1.0,0.0,0.0] # l1 loss, loss (2), loss (3)
    
training_configs:
    num_epochs: 12
    loss_fn: 'huber' #'my_joint_loss' #'berhu' 
    lr: 0.0001 #0.0002 #0.01
    outpath:      '/home/hankm/results/neuro_exploration_res/viz_net'
    outmodelfile: '/home/hankm/results/neuro_exploration_res/viz_net/viznet_iros24'
    outhistfile:  '/home/hankm/results/neuro_exploration_res/viz_net/viznet_iros24_hist'
    
testing_configs:
    metric_fn: 'maxpot_euc_dist' #'rel_potdiff' #'mae' #'rmse' #
    #loss_fn: 'max_euc_dist'
